'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Admin_aspx
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("r2i.OWS.Wrapper.DNN.Admin.aspx", GetType(Admin_aspx).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {&quot;Name&quot;:&quot;OWS.Configuration.EventLog&quot;,&quot;ConfigurationID&quot;:&quot;12029631-8826-86ee-cd1e-9da1abf43dcf&quot;,&quot;searchItems&quot;:[],&quot;queryItems&quot;:null,&quot;listItems&quot;:null,&quot;messageItems&quot;:[{&quot;Index&quot;:1,&quot;Level&quot;:0,&quot;Parameters&quot;:{&quot;Name&quot;:&quot;OnLoad&quot;,&quot;RenderType&quot;:&quot;0&quot;,&quot;skipDebug&quot;:&quot;False&quot;,&quot;includeSearch&quot;:&quot;False&quot;},&quot;ActionType&quot;:&quot;Action-Region&quot;,&quot;ChildActions&quot;:[{&quot;Index&quot;:2,&quot;Level&quot;:0,&quot;Parameters&quot;:{&quot;Type&quot;:&quot;&amp;lt;Action&amp;gt;&quot;,&quot;Name&quot;:&quot;StatusMessage&quot;,&quot;Value&quot;:&quot;&quot;,&quot;SkipProcessing&quot;:&quot;false&quot;,&quot;AssignmentType&quot;:&quot;0&quot;},&quot;ActionType&quot;:&quot;Action-Assignment&quot;,&quot;ChildActions&quot;:[]}, [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property OWS_Configuration_Events() As String
            Get
                Return ResourceManager.GetString("OWS.Configuration.Events", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {&quot;Name&quot;:&quot;OWSConfiguration.List&quot;,&quot;ConfigurationID&quot;:&quot;12025045-0297-2e6a-f9a5-00171c237eb2&quot;,&quot;searchItems&quot;:[],&quot;queryItems&quot;:[],&quot;listItems&quot;:[],&quot;messageItems&quot;:[{&quot;Index&quot;:1,&quot;Level&quot;:0,&quot;Parameters&quot;:{&quot;Name&quot;:&quot;OnLoad&quot;,&quot;RenderType&quot;:&quot;0&quot;,&quot;skipDebug&quot;:&quot;False&quot;,&quot;includeSearch&quot;:&quot;False&quot;},&quot;ActionType&quot;:&quot;Action-Region&quot;,&quot;ChildActions&quot;:[{&quot;Index&quot;:2,&quot;Level&quot;:0,&quot;Parameters&quot;:{&quot;Type&quot;:&quot;&amp;lt;Action&amp;gt;&quot;,&quot;Name&quot;:&quot;StatusMessage&quot;,&quot;Value&quot;:&quot;&quot;,&quot;SkipProcessing&quot;:&quot;false&quot;,&quot;AssignmentType&quot;:&quot;0&quot;},&quot;ActionType&quot;:&quot;Action-Assignment&quot;,&quot;ChildActions&quot;:[]},{&quot;Index&quot;: [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property OWS_Configuration_List() As String
            Get
                Return ResourceManager.GetString("OWS.Configuration.List", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {&quot;Name&quot;:&quot;OWSConfiguration.List&quot;,&quot;ConfigurationID&quot;:&quot;12025045-0297-2e6a-f9a5-00171c237eb2&quot;,&quot;searchItems&quot;:[],&quot;queryItems&quot;:[],&quot;listItems&quot;:[],&quot;messageItems&quot;:[{&quot;Index&quot;:1,&quot;Level&quot;:0,&quot;Parameters&quot;:{&quot;Name&quot;:&quot;OnLoad&quot;,&quot;RenderType&quot;:&quot;0&quot;,&quot;skipDebug&quot;:&quot;False&quot;,&quot;includeSearch&quot;:&quot;False&quot;},&quot;ActionType&quot;:&quot;Action-Region&quot;,&quot;ChildActions&quot;:[{&quot;Index&quot;:2,&quot;Level&quot;:1,&quot;Parameters&quot;:{&quot;Value&quot;:&quot;Place all general operations within this region as a starting point. This includes Template and Variable assignments.&quot;},&quot;ActionType&quot;:&quot;Action-Comment&quot;,&quot;ChildA [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property OWS_Configuration_List_Exporter() As String
            Get
                Return ResourceManager.GetString("OWS.Configuration.List.Exporter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {&quot;Name&quot;:&quot;OWS.Configuration.Repository&quot;,&quot;ConfigurationID&quot;:&quot;12029631-8826-86ee-cd1e-9da1abf43dce&quot;,&quot;searchItems&quot;:[],&quot;queryItems&quot;:null,&quot;listItems&quot;:null,&quot;messageItems&quot;:[{&quot;Index&quot;:1,&quot;Level&quot;:0,&quot;Parameters&quot;:{&quot;Name&quot;:&quot;OnLoad&quot;,&quot;RenderType&quot;:&quot;0&quot;,&quot;skipDebug&quot;:&quot;False&quot;,&quot;includeSearch&quot;:&quot;False&quot;},&quot;ActionType&quot;:&quot;Action-Region&quot;,&quot;ChildActions&quot;:[{&quot;Index&quot;:2,&quot;Level&quot;:0,&quot;Parameters&quot;:{&quot;Name&quot;:&quot;Query Variables&quot;,&quot;RenderType&quot;:&quot;0&quot;,&quot;skipDebug&quot;:&quot;False&quot;,&quot;includeSearch&quot;:&quot;False&quot;},&quot;ActionType&quot;:&quot;Action-Region&quot;,&quot;ChildActions&quot;:[{&quot;Index&quot;:3,&quot;Level&quot;:0,&quot;P [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property OWS_Configuration_Repository() As String
            Get
                Return ResourceManager.GetString("OWS.Configuration.Repository", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
